-- =================================================================================
-- V1: Baseline Inicial do Sistema
-- =================================================================================

-- 1. TABELAS INDEPENDENTES (Sem chaves estrangeiras)
CREATE TABLE tipo_etnia (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            tipo VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE curso (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       ativo BOOLEAN NOT NULL,
                       nome VARCHAR(255) UNIQUE,
                       numero_periodos INTEGER NOT NULL
);

CREATE TABLE documento (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nome VARCHAR(255),
                           path VARCHAR(255)
);

CREATE TABLE tipo_unidade_administrativa (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             nome VARCHAR(255) UNIQUE
);

-- 2. TABELAS BASE (Com dependências simples)
CREATE TABLE usuario (
                         id UUID PRIMARY KEY,
                         ativo BOOLEAN,
                         cpf VARCHAR(255) UNIQUE,
                         email VARCHAR(255) UNIQUE,
                         nome VARCHAR(255),
                         nome_social VARCHAR(255),
                         telefone VARCHAR(255),
                         tipo_etnia_id BIGINT REFERENCES tipo_etnia(id)
);

-- Herança JOINED: Tabela pai
CREATE TABLE perfil (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        foto_perfil OID, -- PostgreSQL mapeia @Lob byte[] para OID
                        usuario_id UUID REFERENCES usuario(id)
);

CREATE TABLE unidade_administrativa (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        codigo VARCHAR(255) NOT NULL UNIQUE,
                                        nome VARCHAR(255) NOT NULL,
                                        tipo_unidade_administrativa_id BIGINT NOT NULL REFERENCES tipo_unidade_administrativa(id),
                                        unidade_pai_id BIGINT REFERENCES unidade_administrativa(id)
);

-- 3. TABELAS FILHAS (Herança do Perfil)
CREATE TABLE aluno (
                       matricula VARCHAR(255) UNIQUE,
                       curso_id BIGINT REFERENCES curso(id),
                       id BIGINT PRIMARY KEY REFERENCES perfil(id)
);

CREATE TABLE funcionario (
                             siape VARCHAR(255),
                             id BIGINT PRIMARY KEY REFERENCES perfil(id)
);

CREATE TABLE visitante (
                           id BIGINT PRIMARY KEY REFERENCES perfil(id)
);

-- 4. TABELAS NETAS (Herança de Funcionario)
CREATE TABLE gestor (
                        id BIGINT PRIMARY KEY REFERENCES funcionario(id)
);

CREATE TABLE professor (
                           id BIGINT PRIMARY KEY REFERENCES funcionario(id)
);

CREATE TABLE tecnico (
                         id BIGINT PRIMARY KEY REFERENCES funcionario(id)
);

-- 5. TABELAS DE RELACIONAMENTO E OPERACIONAIS
CREATE TABLE solicitacao_perfil (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    data_avaliacao TIMESTAMP(6) WITHOUT TIME ZONE,
                                    data_solicitacao TIMESTAMP(6) WITHOUT TIME ZONE,
                                    parecer VARCHAR(255),
                                    perfil_solicitado VARCHAR(255),
                                    status SMALLINT, -- Enum mapeado sem @Enumerated(STRING) vira ordinal (0, 1, 2)
                                    perfil_id BIGINT UNIQUE REFERENCES perfil(id),
                                    responsavel_id UUID REFERENCES usuario(id),
                                    solicitante_id UUID REFERENCES usuario(id)
);

CREATE TABLE gestor_unidade (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                papel VARCHAR(255),
                                gestor_id BIGINT REFERENCES gestor(id),
                                unidade_administrativa_id BIGINT REFERENCES unidade_administrativa(id)
);

-- 6. TABELAS DE JOIN (ManyToMany ou OneToMany unidirecional)
CREATE TABLE professor_cursos (
                                  professor_id BIGINT NOT NULL REFERENCES professor(id),
                                  cursos_id BIGINT NOT NULL REFERENCES curso(id),
                                  PRIMARY KEY (professor_id, cursos_id)
);

CREATE TABLE solicitacao_perfil_documentos (
                                               solicitacao_perfil_id BIGINT NOT NULL REFERENCES solicitacao_perfil(id),
                                               documentos_id BIGINT NOT NULL UNIQUE REFERENCES documento(id)
);

CREATE TABLE ua_funcionarios (
                                 ua_id BIGINT NOT NULL REFERENCES unidade_administrativa(id),
                                 funcionario_id BIGINT NOT NULL REFERENCES funcionario(id),
                                 PRIMARY KEY (ua_id, funcionario_id)
);